// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Canon_sampling
SEXP Canon_sampling(SEXP xin, SEXP yin, SEXP gRNAin, SEXP Gibbsnumberin, SEXP burninproportion, SEXP initial_betain, SEXP initial_gammain, SEXP pi_beta_shape_in, SEXP pi_beta_scale_in, SEXP a_betain, SEXP b_betain, SEXP sigma_dfin, SEXP verbosein);
RcppExport SEXP _Canon_Canon_sampling(SEXP xinSEXP, SEXP yinSEXP, SEXP gRNAinSEXP, SEXP GibbsnumberinSEXP, SEXP burninproportionSEXP, SEXP initial_betainSEXP, SEXP initial_gammainSEXP, SEXP pi_beta_shape_inSEXP, SEXP pi_beta_scale_inSEXP, SEXP a_betainSEXP, SEXP b_betainSEXP, SEXP sigma_dfinSEXP, SEXP verboseinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type gRNAin(gRNAinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gibbsnumberin(GibbsnumberinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type burninproportion(burninproportionSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initial_betain(initial_betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initial_gammain(initial_gammainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_shape_in(pi_beta_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_scale_in(pi_beta_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a_betain(a_betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_betain(b_betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma_dfin(sigma_dfinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbosein(verboseinSEXP);
    rcpp_result_gen = Rcpp::wrap(Canon_sampling(xin, yin, gRNAin, Gibbsnumberin, burninproportion, initial_betain, initial_gammain, pi_beta_shape_in, pi_beta_scale_in, a_betain, b_betain, sigma_dfin, verbosein));
    return rcpp_result_gen;
END_RCPP
}
// Canon_sampling_off_target
SEXP Canon_sampling_off_target(SEXP xin, SEXP yin, SEXP gRNAin, SEXP Gibbsnumberin, SEXP burninproportion, SEXP initial_betain, SEXP initial_gammain, SEXP pi_beta_shape_in, SEXP pi_beta_scale_in, SEXP a_betain, SEXP b_betain, SEXP pi_eta_shape_in, SEXP pi_eta_scale_in, SEXP a_etain, SEXP b_etain, SEXP sigma_dfin, SEXP verbosein);
RcppExport SEXP _Canon_Canon_sampling_off_target(SEXP xinSEXP, SEXP yinSEXP, SEXP gRNAinSEXP, SEXP GibbsnumberinSEXP, SEXP burninproportionSEXP, SEXP initial_betainSEXP, SEXP initial_gammainSEXP, SEXP pi_beta_shape_inSEXP, SEXP pi_beta_scale_inSEXP, SEXP a_betainSEXP, SEXP b_betainSEXP, SEXP pi_eta_shape_inSEXP, SEXP pi_eta_scale_inSEXP, SEXP a_etainSEXP, SEXP b_etainSEXP, SEXP sigma_dfinSEXP, SEXP verboseinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type gRNAin(gRNAinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gibbsnumberin(GibbsnumberinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type burninproportion(burninproportionSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initial_betain(initial_betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initial_gammain(initial_gammainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_shape_in(pi_beta_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_scale_in(pi_beta_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a_betain(a_betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_betain(b_betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_eta_shape_in(pi_eta_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_eta_scale_in(pi_eta_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a_etain(a_etainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_etain(b_etainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma_dfin(sigma_dfinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbosein(verboseinSEXP);
    rcpp_result_gen = Rcpp::wrap(Canon_sampling_off_target(xin, yin, gRNAin, Gibbsnumberin, burninproportion, initial_betain, initial_gammain, pi_beta_shape_in, pi_beta_scale_in, a_betain, b_betain, pi_eta_shape_in, pi_eta_scale_in, a_etain, b_etain, sigma_dfin, verbosein));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Canon_Canon_sampling", (DL_FUNC) &_Canon_Canon_sampling, 13},
    {"_Canon_Canon_sampling_off_target", (DL_FUNC) &_Canon_Canon_sampling_off_target, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_Canon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
